### ISSUE TITLE
ScriptEvaluator is not thread-safe

### ISSUE THREAD

**Issue by dmytro-gundartsev** [camunda-community-hub/script-connector#255]
Cached script engines stored as a singletone Map. All the threads, reusing the same cached script engines, may bump into the problem of undesired reset of the context input variables. It happens when we have BPMN process with two parallel ScriptTasks having the same set of the input variables. It happens, that two parallel threads are initializing the engine-wide variables, which corrupts the execution of the script by unpredictable change of the variable value of the script is being already executed by other thread.
**Pieces of the code causing the problem**:

`private final Map<String, ScriptEngine> cachedScriptEngines = new HashMap<>();`
and this:
```
final ScriptContext context = scriptEngine.getContext();
    final Bindings bindings = context.getBindings(ScriptContext.ENGINE_SCOPE);
    bindings.putAll(variables);
```
**Proposed solution**
to make the Map ThreadLocal, guaranteeing that each instance of the cached ScriptEngines will perform one script at the time.

**Comment by saig0** [comment]
@dmytro-gundartsev interesting. Thank you for raising this up. :+1: 

Feel free to contribute a fix. :rocket:

**Comment by jonathanlukas** [comment]
Closing this issue as there was no contribution for a year
